services:
  # redis:
  #   image: redis:latest
  #   container_name: eventr_redis
  #   ports:
  #     - "6379:6379"
  #   restart: on-failure

  postgres:
    image: postgres:latest
    container_name: shelf_savvy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    restart: on-failure
