-- AlterTable
ALTER TABLE "User" ADD COLUMN     "lastCheckIn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "totalPoints" INTEGER NOT NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE "Achivements" ADD CONSTRAINT "Achivements_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
